service: conn-leak
# app and org for use with dashboard.serverless.com
#app: conn-leak
#org: dgkimnet


provider:
  name: aws
  runtime: nodejs12.x

  region: ap-northeast-2

  vpc:
    securityGroupIds:
      - sg-ed636484
    subnetIds:
      - subnet-b9314dd0

  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"
  environment:
    RDS_DATABASE: ${env:RDS_DATABASE}
    RDS_HOSTNAME: ${env:RDS_HOSTNAME}
    RDS_PASSWORD: ${env:RDS_PASSWORD}
    RDS_PORT: ${env:RDS_PORT}
    RDS_USERNAME: ${env:RDS_USERNAME}
    sql: "SELECT NOW"

custom:
  currentStage: ${opt:stage, self:provider.stage}
  serverlessIfElse:
    - If: '"${self:custom.currentStage}" == "prod"'
      Set:
        provider.environment.sql: "SELECT NOW()"
      ElseSet:
        provider.environment.sql: "SELECT NOW"

plugins:
  - serverless-plugin-ifelse

package:
  exclude:
    - inside.sh

functions:
  hello:
    handler: handler.hello
    events:
      - schedule:
          rate: rate(1 minute)
          enabled: true

